AWSTemplateFormatVersion: '2010-09-09'
Description: 'Main CloudFormation template for Multi-Channel GenAI Demo with nested OpenSearch stack and Secrets Manager'

Parameters:
  CdkAppName:
    Type: String
    Default: 'MultiChannelGenAIDemo'

Resources:
  MessagingSecrets:
    Type: 'AWS::SecretsManager::Secret'
    Properties:
      Name: !Sub '/${CdkAppName}/messaging-secrets'
      Description: 'Secrets for SMS and WhatsApp origination numbers'
      GenerateSecretString:
        SecretStringTemplate: '{"OriginationNumberId":"", "WhatsappOriginationNumberId":""}'
        GenerateStringKey: 'dummy'
        ExcludeCharacters: '"@/\'

  AccessLogsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      VersioningConfiguration:
        Status: Enabled
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true

  DocsBucket:
    Type: 'AWS::S3::Bucket'
    Properties:
      LifecycleConfiguration:
        Rules:
          - ExpirationInDays: 10
            Status: Enabled
      PublicAccessBlockConfiguration:
        BlockPublicAcls: true
        BlockPublicPolicy: true
        IgnorePublicAcls: true
        RestrictPublicBuckets: true
      BucketEncryption:
        ServerSideEncryptionConfiguration:
          - ServerSideEncryptionByDefault:
              SSEAlgorithm: AES256
      LoggingConfiguration:
        DestinationBucketName: !Ref AccessLogsBucket
        LogFilePrefix: 'kbdocs'

  OpenSearchStack:
    Type: AWS::CloudFormation::Stack
    Properties:
      TemplateBody: 
        !Sub 
          - |
            AWSTemplateFormatVersion: '2010-09-09'
            Description: 'Nested stack for OpenSearch Serverless'

            Resources:
              OpenSearchCollection:
                Type: AWS::OpenSearchServerless::Collection
                Properties:
                  Name: ${CdkAppName}-collection
                  Description: 'Vector store for knowledge base'
                  Type: 'VECTOR_SEARCH'

            Outputs:
              OpenSearchCollectionArn:
                Description: 'ARN of the OpenSearch Serverless Collection'
                Value: !GetAtt OpenSearchCollection.Arn
          - CdkAppName: !Ref CdkAppName
      Parameters:
        CdkAppName: !Ref CdkAppName

  KnowledgeBaseRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: bedrock.amazonaws.com
            Action: sts:AssumeRole
      Policies:
        - PolicyName: KnowledgeBaseAccess
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - s3:GetObject
                  - s3:ListBucket
                Resource:
                  - !Sub arn:aws:s3:::${DocsBucket}
                  - !Sub arn:aws:s3:::${DocsBucket}/*
              - Effect: Allow
                Action:
                  - aoss:APIAccessAll
                Resource: !GetAtt OpenSearchStack.Outputs.OpenSearchCollectionArn

  KnowledgeBase:
    Type: AWS::Bedrock::KnowledgeBase
    Properties:
      Name: !Sub '${CdkAppName}-KnowledgeBase'
      Description: 'Knowledge base for Multi-Channel GenAI Demo'
      KnowledgeBaseConfiguration:
        Type: VECTOR
        VectorKnowledgeBaseConfiguration:
          EmbeddingModelArn: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/amazon.titan-embed-text-v1'
      RoleArn: !GetAtt KnowledgeBaseRole.Arn
      StorageConfiguration:
        Type: OPENSEARCH_SERVERLESS
        OpensearchServerlessConfiguration:
          CollectionArn: !GetAtt OpenSearchStack.Outputs.OpenSearchCollectionArn
          FieldMapping:
            MetadataField: AMAZON_BEDROCK_METADATA
            TextField: AMAZON_BEDROCK_TEXT_CHUNK
            VectorField: bedrock-knowledge-base-default-vector
          VectorIndexName: !Sub '${CdkAppName}-vector-index'

  KnowledgeBaseDataSource:
    Type: AWS::Bedrock::DataSource
    DependsOn:
      - KnowledgeBase
    Properties:
      DataSourceConfiguration:
        Type: S3
        S3Configuration:
          BucketArn: !GetAtt DocsBucket.Arn
      Description: Knowledge Base Data Source
      KnowledgeBaseId: !Ref KnowledgeBase
      Name: !Sub '${CdkAppName}-DataSource'
      VectorIngestionConfiguration:
        ChunkingConfiguration:
          ChunkingStrategy: FIXED_SIZE
          FixedSizeChunkingConfiguration:
            MaxTokens: 300
            OverlapPercentage: 20

  ChatTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub '${CdkAppName}-NotificationTopic'
      KmsMasterKeyId: 'alias/aws/sns'

  WhatsAppChatTopic:
    Type: AWS::SNS::Topic
    Properties:
      DisplayName: !Sub '${CdkAppName}-WhatsAppNotificationTopic'
      KmsMasterKeyId: 'alias/aws/sns'

  SNSRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: 'sms-voice.amazonaws.com'
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: SNSPublishPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action: 'sns:Publish'
                Resource: 
                  - !Ref ChatTopic
                  - !Ref WhatsAppChatTopic

  ChatProcessorLambdaLogGroup:
    Type: AWS::Logs::LogGroup
    Properties:
      RetentionInDays: 90

  ChatProcessorLambda:
    Type: AWS::Lambda::Function
    Properties:
      FunctionName: !Sub '${CdkAppName}-ChatProcessor'
      Runtime: python3.9
      Handler: index.lambda_handler
      Code:
        ZipFile: |
          import os
          import json
          import boto3

          service_name = 'bedrock-agent-runtime'
          client = boto3.client(service_name)

          knowledgeBaseID = os.environ['KNOWLEDGE_BASE_ID']
          foundation_model_ARN = os.environ['FM_ARN']

          def lambda_handler(event, context):
              user_query = event['query']
              
              client_knowledgebase = client.retrieve_and_generate(
                  input={
                      'text': user_query
                  },
                  retrieveAndGenerateConfiguration={
                      'type': 'KNOWLEDGE_BASE',
                      'knowledgeBaseConfiguration': {
                          'knowledgeBaseId': knowledgeBaseID,
                          'modelArn': foundation_model_ARN
                      }
                  }
              )
              
              print("----------- Reference Details -------------")

              citations = client_knowledgebase['citations']
              reference = citations[0]['retrievedReferences'][0]

              s3_location = reference['location']['s3Location']['uri']

              generated_response = client_knowledgebase['output']['text']

              final_result = {
                  'statusCode': 200,
                  'query': user_query,
                  'generated_response': generated_response,
                  's3_location': s3_location
              }
              
              print("Result details:\n", final_result)
              
              return final_result
      Timeout: 30
      MemorySize: 512
      Environment:
        Variables:
          KNOWLEDGE_BASE_ID: !Ref KnowledgeBase
          FM_ARN: !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-v2'
      Role: !GetAtt ChatProcessorLambdaRole.Arn

  ChatProcessorLambdaRole:
    Type: AWS::IAM::Role
    Properties:
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: lambda.amazonaws.com
            Action: 'sts:AssumeRole'
      Policies:
        - PolicyName: ChatProcessorPolicy
          PolicyDocument:
            Version: '2012-10-17'
            Statement:
              - Effect: Allow
                Action:
                  - 'social-messaging:DeleteWhatsAppMessageMedia'
                  - 'social-messaging:SendWhatsAppMessage'
                  - 'social-messaging:PostWhatsAppMessageMedia'
                  - 'social-messaging:GetWhatsAppMessageMedia'
                Resource: !Sub 'arn:aws:social-messaging:${AWS::Region}:${AWS::AccountId}:phone-number-id/*'
              - Effect: Allow
                Action:
                  - 'sms-voice:SendTextMessage'
                  - 'sms-voice:SendMediaMessage'
                Resource: '*'
              - Effect: Allow
                Action:
                  - 'bedrock:InvokeModel'
                  - 'bedrock:Retrieve'
                  - 'bedrock:RetrieveAndGenerate'
                Resource: 
                  - !Sub 'arn:aws:bedrock:${AWS::Region}::foundation-model/anthropic.claude-v2'
                  - !GetAtt KnowledgeBase.Arn
              - Effect: Allow
                Action:
                  - 'logs:CreateLogGroup'
                  - 'logs:CreateLogStream'
                  - 'logs:PutLogEvents'
                Resource: 'arn:aws:logs:*:*:*'

  ChatTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref ChatTopic
      Protocol: lambda
      Endpoint: !GetAtt ChatProcessorLambda.Arn

  WhatsAppChatTopicSubscription:
    Type: AWS::SNS::Subscription
    Properties:
      TopicArn: !Ref WhatsAppChatTopic
      Protocol: lambda
      Endpoint: !GetAtt ChatProcessorLambda.Arn

Outputs:
  ChatProcessorLambdaName:
    Value: !Ref ChatProcessorLambda
  ChatProcessorLambdaARN:
    Value: !GetAtt ChatProcessorLambda.Arn
  DocsBucketName:
    Value: !Ref DocsBucket
  KnowledgeBaseName:
    Value: !Ref KnowledgeBase
  DataSourceName:
    Value: !Ref KnowledgeBaseDataSource
  OpenSearchCollectionArn:
    Value: !GetAtt OpenSearchStack.Outputs.OpenSearchCollectionArn
  MessagingSecretsARN:
    Value: !Ref MessagingSecrets
  ChatTopicARN:
    Value: !Ref ChatTopic
  WhatsAppChatTopicARN:
    Value: !Ref WhatsAppChatTopic
